/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ltDOqLgAgGw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Archivo } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Badge } from "@/components/ui/badge"

interface AcademicsScreenProps {
  onNavigateToHome: () => void;
  onNavigateToProject: () => void; // Add this line
  onNavigatetoContact: () => void;
}

export function AcademicPage({onNavigateToProject, onNavigateToHome, onNavigatetoContact} : AcademicsScreenProps) {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Jonathan van Zyl&apos;s Portfolio</span>
        </Link>
        <nav className="ml-auto flex flex-col gap-4 sm:flex-row sm:gap-6">
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToHome}>
            Home
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary"
            prefetch={false}
            onClick={onNavigateToProject}
          >
            Projects
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary"
            prefetch={false}
          >
            Education
          </Link>
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigatetoContact}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="education" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Education</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Qualifications</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out my educational background and the degrees I&apos;ve earned.
                </p>
              </div>
            </div>
            <div className="flex flex-col gap-8">
              <div className="space-y-2">
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold">Bachelor&apos;s Degree</h3>
                  <p className="text-muted-foreground">
                    Earned a Bachelor of Science in Computer Science from XYZ University.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge>Computer Science</Badge>
                  <Badge>XYZ University</Badge>
                  <Badge>2016-2020</Badge>
                </div>
              </div>
              <div className="space-y-2">
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold">Master&apos;s Degree</h3>
                  <p className="text-muted-foreground">
                    Earned a Master of Science in Data Science from ABC University.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge>Data Science</Badge>
                  <Badge>ABC University</Badge>
                  <Badge>2020-2022</Badge>
                </div>
              </div>
              <div className="space-y-2">
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold">Certification</h3>
                  <p className="text-muted-foreground">
                    Earned a Professional Certificate in Full-Stack Web Development from Coursera.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge>Web Development</Badge>
                  <Badge>Coursera</Badge>
                  <Badge>2022</Badge>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>
        <nav className="sm:ml-auto flex flex-col gap-2 sm:flex-row sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
          <Link href="#" prefetch={false} />
        </nav>
      </footer>
    </div>
  )
}

const MountainIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );


const XIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );

  export {
    MountainIcon,
    XIcon
  };
