/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1VgLxVz8sZi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Archivo } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import Image from "next/image";

import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

interface HomeScreenProps {
  onNavigateToProject: () => void;
}

export function HomeScreen({onNavigateToProject} : HomeScreenProps) {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Jonathan van Zyl&apos;s Portfolio</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Home
          </Link>
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick = {onNavigateToProject}>
            Projects
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Education
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="hero" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Jonathan van Zyl
                </h1>
                <p className="text-muted-foreground md:text-xl">Controls and AI Engineer</p>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                  I&apos;m a passionate engineer with expertise in aerospace, controls and artificial intelligence.
                  My goal is to create innovative solutions that solve real-world problems.
                </p>
                <div className="space-x-4">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                    onClick = {onNavigateToProject}
                  >
                    View Projects
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Contact Me
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Projects</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Work</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out some of the projects I&apos;ve worked on and the technologies I&apos;ve used.
                </p>
              </div>
            </div>
            <div className="mx-auto max-w-5xl">
              <Carousel className="w-full" opts={{ loop: true }}>
                <CarouselContent>
                  <CarouselItem>
                    <Card>
                      <CardHeader>
                        <img
                          src="/QCANet_architecture.svg"
                          width="550"
                          height="310"
                          alt="Project 1"
                          className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                        />
                      </CardHeader>
                      <CardContent className="space-y-2">
                        <div className="space-y-1">
                          <CardTitle>3D CNN for semantic segmentation of mouse embroygeneous.</CardTitle>
                          <CardDescription>
                          3D convolutional neural networks-based segmentation to acquire quantitative criteria of the nucleus during mouse embryogenesis
                          <br />
                          <Link href="https://jvanzyl1.github.io/3D-nuclei-segmentation-reproduction/README.html"
                          target="_blank"
                          rel="noopener noreferrer">
                          Read the Article by clicking here!
                          </Link>
                          </CardDescription>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          <Badge>Artifical Intelligence</Badge>
                          <Badge>Python</Badge>
                          <Badge>Pytorch</Badge>
                          <Badge>OpenCV</Badge>
                        </div>
                      </CardContent>
                    </Card>
                  </CarouselItem>
                  <CarouselItem>
                    <Card>
                      <CardHeader>
                      <img
                        src="/SupplierBizHacks.svg"
                        srcSet="/SupplierBizHacks.svg 1x, /SupplierBizHacks@2x.svg 2x, /SupplierBizHacks@3x.svg 3x"
                        width="550"
                        height="310"
                        alt="Project 2"
                        className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                      />
                      </CardHeader>
                      <CardContent className="space-y-2">
                        <div className="space-y-1">
                          <CardTitle>Cadence</CardTitle>
                          <CardDescription>
                          A take on &apos;To-Good-To-Go&apos; meets &apos;Uber Eats&apos; for preventing food spoilage in bulk selling firms.
                          <br />
                          Entry for BizHack 2024 Hackathon, won &apos;Most Collaborative Team&apos; award.
                          <br />
                          Learn front-end development in 4 hours to make these mockup UIs: 
                          <Link href="https://cadence-tester-gxpb9yx8x-jvanzyl1s-projects.vercel.app/"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="Link">
                           supplier UI
                          </Link> and
                          <Link href="https://cadence-buyer.vercel.app/"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="Link">
                          buyer UI
                          </Link>.
                          </CardDescription>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          <Badge>Frontend</Badge>
                          <Badge>Idea Brainstorming</Badge>
                        </div>
                      </CardContent>
                    </Card>
                  </CarouselItem>
                  <CarouselItem>
                    <Card>
                      <CardHeader>
                      <video
                        src="/DroneWorking.mp4"
                        width="550"
                        height="310"
                        controls
                        className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                      >
                        <track kind="captions" src="/captions.vtt" label="English" srcLang="en" default />
                      </video>
                      </CardHeader>
                      <CardContent className="space-y-2">
                        <div className="space-y-1">
                          <CardTitle>Computer vision and navigation module for drone</CardTitle>
                          <CardDescription>
                          Worked in the paparrazi environment to design a computer vision system for drone navigation.
                          <br />
                          Tested in the TU Delft MAV Lab.
                          </CardDescription>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          <Badge>Computer Vision</Badge>
                          <Badge>C</Badge>
                          <Badge>Python</Badge>
                          <Badge>Drones</Badge>
                          <Badge>OpenCV</Badge>
                        </div>
                      </CardContent>
                    </Card>
                  </CarouselItem>
                  <CarouselItem>
                    <Card>
                      <CardHeader>
                      <img
                        src="/Forze_FuelCell.svg"
                        srcSet="/Forze_FuelCell.svg 1x, /Forze_FuelCell@2x.svg 2x, /Forze_FuelCell@3x.svg 3x"
                        width="550"
                        height="310"
                        alt="Project 4"
                        className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                      />
                      </CardHeader>
                      <CardContent className="space-y-2">
                        <div className="space-y-1">
                          <CardTitle>Forze Hydrogen Racing</CardTitle>
                          <CardDescription>
                          Working on a future Le Mann 24 hour hydrogen race car:
                          <ul style={{ listStyleType: 'disc', paddingLeft: '20px' }}>
                            <li> Anode hydrogen flow control system. </li>
                            <li> Fuel cell software-in-the-loop simulator. </li>
                            <li> Ejector test-bench </li>
                          </ul>
                          </CardDescription>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          <Badge>Matlab/Simulink</Badge>
                          <Badge>Control Systems</Badge>
                          <Badge>Hydrogen Fuel Cells</Badge>
                          <Badge>C++</Badge>
                        </div>
                      </CardContent>
                    </Card>
                  </CarouselItem>
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
            </div>
            <div className="flex justify-center">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                View More on GitHub
              </Link>
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">About Me</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Skills and Experience</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  I&apos;m a skilled software engineer with a passion for building innovative and user-friendly web
                  applications. I have experience working with a variety of technologies and frameworks, and I&apos;m always
                  eager to learn new things.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Front-end Development</h3>
                      <p className="text-muted-foreground">
                        Proficient in React, Next.js, and Tailwind CSS. Experienced in building responsive and
                        accessible user interfaces.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Back-end Development</h3>
                      <p className="text-muted-foreground">
                        Skilled in Node.js, Express, and MongoDB. Experienced in building scalable and secure APIs.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">DevOps</h3>
                      <p className="text-muted-foreground">
                        Familiar with cloud platforms like AWS and Azure. Experienced in setting up CI/CD pipelines and
                        automating deployments.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="About"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section id="education" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Education</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Academic Background</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  I have a strong academic foundation that has prepared me for a successful career in software
                  engineering.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <div className="after:absolute after:inset-y-0 after:w-px after:bg-muted-foreground/20 relative pl-6 after:left-0 grid gap-10">
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
                    <div className="font-medium">June 2016 - Graduated High School</div>
                    <div className="text-muted-foreground">Earned my high school diploma with honors.</div>
                  </div>
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
                    <div className="font-medium">August 2016 - Started University</div>
                    <div className="text-muted-foreground">
                      Began my Bachelor&apos;s degree in Computer Science at the University of California, Berkeley.
                    </div>
                  </div>
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
                    <div className="font-medium">May 2020 - Graduated University</div>
                    <div className="text-muted-foreground">
                      Earned my Bachelor of Science in Computer Science, graduating with honors.
                    </div>
                  </div>
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute left-0 translate-x-[-29.5px] z-10 top-1" />
                    <div className="font-medium">June 2020 - Started Career</div>
                    <div className="text-muted-foreground">
                      Began my career as a software engineer, working on various web development projects.
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <div className="after:absolute after:inset-y-0 after:w-px after:bg-muted-foreground/20 relative pl-6 after:right-0 grid gap-10">
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute right-0 translate-x-[29.5px] z-10 top-1" />
                    <div className="font-medium">High School Diploma</div>
                    <div className="text-muted-foreground">Graduated with Honors</div>
                  </div>
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute right-0 translate-x-[29.5px] z-10 top-1" />
                    <div className="font-medium">Bachelor of Science in Computer Science</div>
                    <div className="text-muted-foreground">University of California, Berkeley</div>
                  </div>
                  <div className="grid gap-1 text-sm relative">
                    <div className="aspect-square w-3 bg-primary rounded-full absolute right-0 translate-x-[29.5px] z-10 top-1" />
                    <div className="font-medium">Graduated with Honors</div>
                    <div className="text-muted-foreground">Magna Cum Laude</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get in Touch</h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                I&apos;d love to hear from you! Feel free to reach out with any questions or opportunities.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex flex-col gap-4">
                <Input type="text" placeholder="Name" className="max-w-lg flex-1" />
                <Input type="email" placeholder="Email" className="max-w-lg flex-1" />
                <Textarea placeholder="Message" className="max-w-lg flex-1" />
                <Button type="submit" className="w-full">
                  Send Message
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
          <Link href="#" prefetch={false} />
        </nav>
      </footer>
    </div>
  )
}

const MountainIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );


const XIcon: React.FC<React.SVGProps<SVGSVGElement>> = (props) => (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );

export {
  MountainIcon,
  XIcon
};