/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wVAkeda0V8l
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Archivo } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { JvZIcon } from "@/components/ui/icons"

interface ProjectScreenProps {
  onNavigateToHome: () => void;
  onNavigateToAcademics: () => void;
  onNavigateToContact: () => void;
}

export function ProjectsPage({onNavigateToHome, onNavigateToAcademics, onNavigateToContact} : ProjectScreenProps) {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <JvZIcon className="h-6 w-6" />
          <span className="sr-only">Jonathan van Zyl&apos;s Portfolio</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToHome}
          >
            Home
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary"
            prefetch={false}
          >
            Projects
          </Link>
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToAcademics}>
            Education
          </Link>
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToContact}
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Projects</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Work</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out some of the projects I&apos;ve worked on and the technologies I&apos;ve used.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 1"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Autonomous Driving System</CardTitle>
                    <CardDescription>
                      A web application that helps users manage their tasks and projects more efficiently.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Evolutionary Algorithms</Badge>
                    <Badge>Model Predictive Control</Badge>
                    <Badge>Python</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 2"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>H2 Anode Control System</CardTitle>
                    <CardDescription>
                      A mobile-friendly e-commerce platform that allows customers to browse and purchase products
                      online.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Control Systems</Badge>
                    <Badge>Matlab/Simulink</Badge>
                    <Badge>FSM</Badge>
                    <Badge>Git</Badge>
                    <Badge>C++</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 3"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>3D Semantic Segmentation of Mouse Nuclei</CardTitle>
                    <CardDescription>
                      A mobile-friendly e-commerce platform that allows customers to browse and purchase products
                      online.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Deep Learning</Badge>
                    <Badge>OOP</Badge>
                    <Badge>Python</Badge>
                    <Badge>Pytorch</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Autonomy computer vision software for a drone </CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Computer Vision</Badge>
                    <Badge>C</Badge>
                    <Badge>Linux OS</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>UAV eVTOL control system to counter urban turbluence </CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Control System Design</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>BizHacks 2024 </CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Front-End</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Anode X Cathode software in the loop simulator </CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Matlab/Simulink</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Multi-Objective Optimisation of Vehicle Routing Problem</CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Python</Badge>
                    <Badge>Operations Research</Badge>
                    <Badge>Git</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Various AI projects.</CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Python</Badge>
                    <Badge>Artificial Intelligence</Badge>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex justify-center">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                View More on GitHub
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Jonathan van Zyl. All rights reserved.</p>
      </footer>
    </div>
  )
}