/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wVAkeda0V8l
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Archivo } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { JvZIcon } from "@/components/ui/icons"

interface ProjectScreenProps {
  onNavigateToHome: () => void;
  onNavigateToAcademics: () => void;
  onNavigateToContact: () => void;
}

export function ProjectsPage({onNavigateToHome, onNavigateToAcademics, onNavigateToContact} : ProjectScreenProps) {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <JvZIcon className="h-6 w-6" />
          <span className="sr-only">Jonathan van Zyl&apos;s Portfolio</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToHome}
          >
            Home
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4 text-primary"
            prefetch={false}
          >
            Projects
          </Link>
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToAcademics}>
            Education
          </Link>
          <Link href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
          onClick={onNavigateToContact}
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Projects</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Work</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Check out some of the projects I&apos;ve worked on and the technologies I&apos;ve used.
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardHeader>
                  <img
                    src="/InfosysGolfBuggy.png"
                    width="550"
                    height="310"
                    alt="Project 1"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Autonomous Driving System</CardTitle>
                    <CardDescription>
                      Developed non-linear simulation models for a driving system, using OOP
                      methods to create Partical Swarm Optimisation and Genetic Algorithms with subwswarms and island migration
                      respectively, these were used used these to fit the model&apos;s parameters and tune
                      controler gains. Additionally automatic linearisation of the model for use in a linear
                      Model Predictive Controller for trajectory tracking, was implemented.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Evolutionary Algorithms</Badge>
                    <Badge>Model Predictive Control</Badge>
                    <Badge>Python</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/Forze_FuelCell.png"
                    width="550"
                    height="310"
                    alt="Project 2"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Fuel-Cell Control System</CardTitle>
                    <CardDescription>
                      During time at Forze Hydrogen Racing, developed parts of a fuel cell control system. <br/>
                      <ul className="list-disc pl-5 space-y-1">
                        <li><em>Anode Testbench:</em> created a grey box model of the anode system
                        from first principles and system identification. This was used to tune the
                        control system for the anode first upon simulation, then upon the testbench.</li>
                        <li><em>Fuel Cell supply system Software-In-Loop Simulator:</em> combined the models
                        of anode with a pre-made cathode model, merged with the finite state machines (FSMs) to operate
                        systems for the fuel cell. Provided a platform for the control system to be tested, to 
                        ensure the control system was working as intended. </li>
                        <li><em>Dry fuel cell testbench:</em> contributed to development of the FSMs needed 
                        to safely operate the fuel cell testbench.</li>
                        <li><em>Ejector testbench:</em> developed the control system files (Matlab/Simulink), and software (C++)
                        to run the testbench. Secondly, developed the FSMs, testbench and simulation framework. Finally, 
                        built a wiring harness to operate the testbench, and started to dry test it along with the software. Before 
                        running into issues with the embedded system itself.
                        </li>
                      </ul>                    
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Control Systems</Badge>
                    <Badge>Matlab/Simulink</Badge>
                    <Badge>FSM</Badge>
                    <Badge>Git</Badge>
                    <Badge>C++</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/QCANet_architecture.png"
                    width="550"
                    height="310"
                    alt="Project 3"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>3D Semantic Segmentation of Mouse Nuclei</CardTitle>
                    <CardDescription>
                      Reproduced and evaluated the performance of QCANet, a novel approach
                      for instance segmentation in 3D fluroscence microscopy images, which combines
                      semantic segmentation with marker-based watershed techniques. Despite achieving satisfactory visual results,
                      significant quantitative discrepanices with the original study were observed, highlighting
                      challenges in hyperparameter tuning and reporoducibility. <br />
                      Blog is available: <Link href="https://jvanzyl1.github.io/3D-nuclei-segmentation-reproduction/README.html" className="text-primary" target="_blank" rel="noopener noreferrer">here</Link>. <br />
                      Code is available: <Link href="https://github.com/JvanZyl1/3D-nuclei-segmentation-reproduction" className="text-primary" target="_blank" rel="noopener noreferrer">here</Link>. <br />
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Deep Learning</Badge>
                    <Badge>OOP</Badge>
                    <Badge>Python</Badge>
                    <Badge>Pytorch</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/OpticalFlow.png"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Autonomy computer vision software for a drone </CardTitle>
                    <CardDescription>
                      Using the  <a href="https://wiki.paparazziuav.org/wiki/Main_Page" className="text-primary" target="_blank" rel="noopener noreferrer">Paparrazi UAV</a> 
                      software, developed computer vision and navigation software with a team of my peers. Tested this in the 
                      <a  href="https://gazebosim.org/home" className="text-primary" target="_blank" rel="noopener noreferrer"> Gazebo</a> environment, aboard a Linus OS. 
                      This allowed the drone to autonomously navigate a course, and avoid obstacles within TU Delft&apos;s Cyberzoo. This provided 
                      hands-on experience in working with C, Linux OS and computer vision software. Projection, edge detection, background segmentation and 
                      optical flow were researched and trialled during this project.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Computer Vision</Badge>
                    <Badge>C</Badge>
                    <Badge>Linux OS</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/VeatleCFD.png"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>UAV eVTOL control system to counter urban turbluence </CardTitle>
                    <CardDescription>
                    May 2022 - June 2022 <br />
                    Design Synthesis Exercise, a 10 week group project for BSc Aerospace students at TU Delft for graduation. <br />
                    Brief: The design of an autonomous, sustainable, low-noise, electric vertical take-off Urban Air Mobility Vehicle
                    with a focus on control under urban turbulence. My part mainly focused on building a 6 degree of freedom controls model.
                    To simulate and control the vehicle&apos;s response to a 8 Beaufort gust and wake around the Shard building in London. <br />
                    <em>Presented at AIAA Student Conference 2022.</em> <br />
                    <em>Sponsored by Eve, a subsidiary of Embraer.</em>
                    <em>Awarded a grade of 8.5</em>

                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Control System Design</Badge>
                    <Badge>Model Predictive Control</Badge>
                    <Badge>Matlab/Simulink</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Websites </CardTitle>
                    <CardDescription>
                    Learned how to make front-end of website in a few hours during the 2024 iteration of the 
                    BizHacks hackathon in Bengaluru, India. Here I made two bare-boned UI&apos;s for a platform 
                    called <em>Cadence</em>. This was inspired by To-Good-To-Go, but for wholesale suppliers, along 
                    with an inventory management system: the aim to prevent food waste. <br />
                    <em>Won Most Colloborative Team Award</em> <br />
                    Following, decided to make the website you are seeing here, improving my skills through self-learning. <br />
                    Cadence website: <a href = "https://cadence-buyer-rgy48akyt-jvanzyl1s-projects.vercel.app/" className="text-primary" target="_blank" rel="noopener noreferrer">buyer</a>
                    and <a href = "https://cadence-tester-gxpb9yx8x-jvanzyl1s-projects.vercel.app/" className="text-primary" target="_blank" rel="noopener noreferrer">seller</a>. Please 
                    note, I had no experience in website design before this.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Front-End</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Learning To Play Pacman from MsPacman </CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Matlab/Simulink</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="550"
                    height="310"
                    alt="Project 4"
                    className="mx-auto aspect-video overflow-hidden rounded-t-xl object-cover object-center"
                  />
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <CardTitle>Multi-Objective Optimisation of Vehicle Routing Problem</CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Python</Badge>
                    <Badge>Operations Research</Badge>
                    <Badge>Git</Badge>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="space-y-2">
                  <div className="space-y-1">
                    <br/>
                    <CardTitle>Various AI projects.</CardTitle>
                    <CardDescription>
                      A data visualization dashboard that helps users analyze and interpret complex data sets.
                    </CardDescription>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge>Python</Badge>
                    <Badge>Artificial Intelligence</Badge>
                  </div>
                </CardContent>
              </Card>
            </div>
            <div className="flex justify-center">
              <Link
                href="https://github.com/JvanZyl1"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
                target = "_blank"
                rel="noopener noreferrer"
              >
                View More on GitHub
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Jonathan van Zyl. All rights reserved.</p>
      </footer>
    </div>
  )
}